create schema if not exists identity;
create schema if not exists contest;
create schema if not exists submission;
create schema if not exists evaluation;
create schema if not exists mentoring;
create schema if not exists file_storage;
create schema if not exists exporting;

create table identity.user_accounts (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password_hash varchar(120) not null,
    account_type varchar(32) not null,
    full_name varchar(240),
    nickname varchar(80),
    bio text,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table identity.user_contacts (
    id bigint generated by default as identity primary key,
    user_id bigint not null references identity.user_accounts(id) on delete cascade,
    type varchar(32) not null,
    value varchar(320) not null,
    primary_contact boolean not null default false
);

create table identity.access_tokens (
    id bigint generated by default as identity primary key,
    token_id varchar(80) not null unique,
    user_id bigint not null references identity.user_accounts(id) on delete cascade,
    expires_at timestamptz not null,
    created_at timestamptz not null,
    revoked_at timestamptz
);

create index idx_access_tokens_user on identity.access_tokens(user_id);
create index idx_access_tokens_expires_at on identity.access_tokens(expires_at);

create table contest.contests (
    id bigint generated by default as identity primary key,
    title varchar(240) not null,
    description text,
    rules text,
    status varchar(32) not null,
    participation_mode varchar(32) not null,
    min_team_size integer,
    max_team_size integer,
    registration_ends_at date,
    team_building_ends_at date,
    starts_at date,
    ends_at date,
    contacts text,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table contest.contest_organizers (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    user_id bigint not null references identity.user_accounts(id) on delete cascade,
    role varchar(32) not null,
    unique (contest_id, user_id, role)
);

create index idx_contest_organizers_user on contest.contest_organizers(user_id);

create table contest.contest_stages (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    sort_order integer not null,
    title varchar(240) not null,
    description text,
    rules text,
    extra_info text,
    deadline_at timestamptz,
    eliminating boolean not null default false,
    score_scale varchar(32) not null,
    unique (contest_id, sort_order)
);

create table contest.contest_resources (
    id bigint generated by default as identity primary key,
    stage_id bigint not null references contest.contest_stages(id) on delete cascade,
    sort_order integer not null,
    type varchar(32) not null,
    title varchar(180) not null,
    description text,
    link_url varchar(1000),
    file_id bigint
);

create table contest.submission_fields (
    id bigint generated by default as identity primary key,
    stage_id bigint not null references contest.contest_stages(id) on delete cascade,
    sort_order integer not null,
    title varchar(160) not null,
    type varchar(32) not null,
    required boolean not null default false,
    file_formats varchar(240),
    max_file_size_mb integer,
    options text,
    participant_hint text,
    example_value text,
    expert_note text,
    criteria_description text,
    unique (stage_id, sort_order)
);

create table contest.contest_registrations (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    participant_id bigint not null references identity.user_accounts(id) on delete cascade,
    registered_at timestamptz not null,
    unique (contest_id, participant_id)
);

create table contest.teams (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    leader_id bigint not null references identity.user_accounts(id),
    name varchar(160) not null,
    invite_token varchar(80) not null unique,
    created_at timestamptz not null
);

create table contest.team_members (
    id bigint generated by default as identity primary key,
    team_id bigint not null references contest.teams(id) on delete cascade,
    participant_id bigint not null references identity.user_accounts(id) on delete cascade,
    joined_at timestamptz not null,
    unique (team_id, participant_id)
);

create table contest.team_join_requests (
    id bigint generated by default as identity primary key,
    team_id bigint not null references contest.teams(id) on delete cascade,
    participant_id bigint not null references identity.user_accounts(id) on delete cascade,
    status varchar(32) not null,
    created_at timestamptz not null
);

create table submission.projects (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    team_id bigint references contest.teams(id) on delete cascade,
    owner_participant_id bigint references identity.user_accounts(id) on delete cascade,
    created_at timestamptz not null,
    constraint project_owner_check check (
        (team_id is not null and owner_participant_id is null)
        or (team_id is null and owner_participant_id is not null)
    )
);

create unique index ux_project_team on submission.projects(contest_id, team_id) where team_id is not null;
create unique index ux_project_participant on submission.projects(contest_id, owner_participant_id) where owner_participant_id is not null;

create table submission.stage_submissions (
    id bigint generated by default as identity primary key,
    project_id bigint not null references submission.projects(id) on delete cascade,
    stage_id bigint not null references contest.contest_stages(id) on delete cascade,
    status varchar(32) not null,
    submitted_by bigint references identity.user_accounts(id),
    submitted_at timestamptz,
    created_at timestamptz not null,
    unique (project_id, stage_id)
);

create table submission.submission_values (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references submission.stage_submissions(id) on delete cascade,
    field_id bigint not null references contest.submission_fields(id) on delete cascade,
    value_text text,
    file_ids text,
    unique (submission_id, field_id)
);

create table evaluation.review_assignments (
    id bigint generated by default as identity primary key,
    stage_id bigint not null references contest.contest_stages(id) on delete cascade,
    submission_id bigint not null references submission.stage_submissions(id) on delete cascade,
    expert_id bigint not null references identity.user_accounts(id) on delete cascade,
    status varchar(32) not null,
    assigned_at timestamptz not null,
    score numeric(8, 2),
    comment text,
    finalized_at timestamptz,
    unique (submission_id, expert_id)
);

create table evaluation.ai_reviews (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references submission.stage_submissions(id) on delete cascade,
    summary text,
    issues text,
    suggested_score numeric(8, 2),
    created_at timestamptz not null
);

create table mentoring.mentor_assignments (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    team_id bigint not null references contest.teams(id) on delete cascade,
    mentor_id bigint not null references identity.user_accounts(id) on delete cascade,
    assigned_at timestamptz not null,
    unique (team_id, mentor_id)
);

create table mentoring.mentor_comments (
    id bigint generated by default as identity primary key,
    stage_submission_id bigint not null references submission.stage_submissions(id) on delete cascade,
    mentor_id bigint not null references identity.user_accounts(id) on delete cascade,
    text text not null,
    created_at timestamptz not null
);

create table mentoring.mentor_calls (
    id bigint generated by default as identity primary key,
    team_id bigint not null references contest.teams(id) on delete cascade,
    mentor_id bigint not null references identity.user_accounts(id) on delete cascade,
    starts_at timestamptz not null,
    ends_at timestamptz not null,
    link varchar(500),
    notes text
);

create table file_storage.stored_files (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references identity.user_accounts(id) on delete cascade,
    bucket varchar(120) not null,
    object_key varchar(500) not null unique,
    original_filename varchar(255) not null,
    content_type varchar(120),
    size_bytes bigint not null,
    created_at timestamptz not null
);

create table exporting.export_jobs (
    id bigint generated by default as identity primary key,
    contest_id bigint not null references contest.contests(id) on delete cascade,
    created_by bigint not null references identity.user_accounts(id),
    format varchar(32) not null,
    custom_prompt text,
    created_at timestamptz not null
);
